"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("posts", [
      {
        id: 1,
        userId: 1,
        category: "맛집",
        views: 0,
        contents: "여기 맛집입니다.",
        img: "",
        location: "",
        comment_cnt: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        userId: 1,
        category: "맛집",
        views: 0,
        contents: "짬밥이 더맛있어요",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        userId: 1,
        category: "맛집",
        views: 0,
        contents: "비비고 만두가짱",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        userId: 1,
        category: "취미",
        views: 0,
        contents: "취미1.",
        img: "",
        location: "",
        comment_cnt: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        userId: 1,
        category: "취미",
        views: 0,
        contents: "취미2",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        userId: 1,
        category: "취미",
        views: 0,
        contents: "취미3",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        userId: 1,
        category: "반려동물",
        views: 0,
        contents: "반려동물1.",
        img: "",
        location: "",
        comment_cnt: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        userId: 1,
        category: "반려동물",
        views: 0,
        contents: "반려동물2",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        userId: 1,
        category: "반려동물",
        views: 0,
        contents: "반려동물3",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        userId: 1,
        category: "동네소식",
        views: 0,
        contents: "동네소식1.",
        img: "",
        location: "",
        comment_cnt: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        userId: 1,
        category: "동네소식",
        views: 0,
        contents: "동네소식2",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        userId: 1,
        category: "동네소식",
        views: 0,
        contents: "동네소식3",
        img: "",
        location: "",
        comment_cnt: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("posts", null, {});
  },
};
